pub mod defect;
pub mod ironclad;
pub mod shared;
pub mod silent;
pub mod watcher;

use crate::utils::NotImplemented;
use serde::{Serialize, Deserialize};

use super::{
    card_trait::{Card, MasterCard},
    CardName,
};

#[derive(Debug, Serialize, Deserialize)]
pub enum ConcreteCard {
    Strike(shared::strike::Strike),
    Defend(shared::defend::Defend),
    Bash(ironclad::bash::Bash),
    Void(shared::void::Void),
    ShrugItOff(ironclad::shrugitoff::ShrugItOff),
    Cleave(ironclad::cleave::Cleave),
    Clothesline(ironclad::clothesline::Clothesline),
    Carnage(ironclad::carnage::Carnage),
    Anger(ironclad::anger::Anger),
    GhostlyArmor(ironclad::ghostlyarmor::GhostlyArmor),
    Barricade(ironclad::barricade::Barricade),
    Armaments(ironclad::armaments::Armaments),
    Bloodletting(ironclad::bloodletting::Bloodletting),
    BodySlam(ironclad::bodyslam::BodySlam),
    Bludgeon(ironclad::bludgeon::Bludgeon),
    Impervious(ironclad::impervious::Impervious),
    Clash(ironclad::clash::Clash),
    //Flex(ironclad::flex::Flex),
    Havoc(ironclad::havoc::Havoc),
    //Headbutt(ironclad::headbutt::Headbutt),
    HeavyBlade(ironclad::heavyblade::HeavyBlade),
    IronWave(ironclad::ironwave::IronWave),
    PerfectedStrike(ironclad::perfectedstrike::PerfectedStrike),
    PommelStrike(ironclad::pommelstrike::PommelStrike),
    SwordBoomerang(ironclad::swordboomerang::SwordBoomerang),
    ThunderClap(ironclad::thunderclap::ThunderClap),
    TrueGrit(ironclad::truegrit::TrueGrit),
    TwinStrike(ironclad::twinstrike::TwinStrike),
    WarCry(ironclad::warcry::WarCry),
    WildStrike(ironclad::wildstrike::WildStrike),
    BattleTrance(ironclad::battletrance::BattleTrance),
    //BloodForBlood(ironclad::bloodforblood::BloodForBlood),
    BurningPact(ironclad::burningpact::BurningPact),
    //Combust(ironclad::combust::Combust),
    DarkEmbrace(ironclad::darkembrace::DarkEmbrace),
    Disarm(ironclad::disarm::Disarm),
    //Dropkick(ironclad::dropkick::Dropkick),
    //DualWield(ironclad::dualwield::DualWield),
    Entrench(ironclad::entrench::Entrench),
    Evolve(ironclad::evolve::Evolve),
    FeelNoPain(ironclad::feelnopain::FeelNoPain),
    FireBreathing(ironclad::firebreathing::FireBreathing),
    //FlameBarrier(ironclad::flamebarrier::FlameBarrier),
    HemoKinesis(ironclad::hemokinesis::HemoKinesis),
    //InfernalBlade(ironclad::infernalblade::InfernalBlade),
    Inflame(ironclad::inflame::Inflame),
    Intimidate(ironclad::intimidate::Intimidate),
    Metallicize(ironclad::metallicize::Metallicize),
    PowerThrough(ironclad::powerthrough::PowerThrough),
    Pummel(ironclad::pummel::Pummel),
    Rage(ironclad::rage::Rage),
    Rampage(ironclad::rampage::Rampage),
    RecklessCharge(ironclad::recklesscharge::RecklessCharge),
    //Rupture(ironclad::rupture::Rupture),
    SearingBlow(ironclad::searingblow::SearingBlow),
    //SecondWind(ironclad::secondwind::SecondWind),
    SeeingRed(ironclad::seeingred::SeeingRed),
    //Sentinel(ironclad::sentinel::Sentinel),
    //SeverSoul(ironclad::seversoul::SeverSoul),
    Shockwave(ironclad::shockwave::Shockwave),
    //SpotWeakness(ironclad::spotweakness::SpotWeakness),
    Uppercut(ironclad::uppercut::Uppercut),
    //Whirlwind(ironclad::whirlwind::Whirlwind),
    Berserk(ironclad::berserk::Berserk),
    //Brutality(ironclad::brutality::Brutality),
    //Corruption(ironclad::corruption::Corruption),
    DemonForm(ironclad::demonform::DemonForm),
    //DoubleTap(ironclad::doubletap::DoubleTap),
    //Exhume(ironclad::exhume::Exhume),
    //Feed(ironclad::feed::Feed),
    //FiendFire(ironclad::fiendfire::FiendFire),
    //Juggernaut(ironclad::juggernaut::Juggernaut),
    //LimitBreak(ironclad::limitbreak::LimitBreak),
    Offering(ironclad::offering::Offering),
    //Reaper(ironclad::reaper::Reaper),
    Apparition(shared::apparition::Apparition),
    //BandageUp(shared::bandage_up::BandageUp),
    //Blind(shared::blind::Blind),
    //DarkShackles(shared::dark_shackles::DarkShackles),
    //DeepBreath(shared::deep_breath::DeepBreath),
    //Discovery(shared::discovery::Discovery),
    //DramaticEntrance(shared::dramatic_entrance::DramaticEntrance),
    //Enlightenment(shared::enlightenment::Enlightenment),
    //Finesse(shared::finesse::Finesse),
    //FlashOfSteel(shared::flash_of_steel::FlashOfSteel),
    //Forethought(shared::forethought::Forethought),
    //GoodInstincts(shared::good_instincts::GoodInstincts),
    //Impatience(shared::impatience::Impatience),
    //JackOfAllTrades(shared::jack_of_all_trades::JackOfAllTrades),
    //Madness(shared::madness::Madness),
    //MindBlast(shared::mind_blast::MindBlast),
    //Panacea(shared::panacea::Panacea),
    //PanicButton(shared::panic_button::PanicButton),
    //Purity(shared::purity::Purity),
    //SwiftStrike(shared::swift_strike::SwiftStrike),
    //Trip(shared::trip::Trip),
    //Apotheosis(shared::apotheosis::Apotheosis),
    //Chrysalis(shared::chrysalis::Chrysalis),
    //HandOfGreed(shared::hand_of_greed::HandOfGreed),
    //Magnetism(shared::magnetism::Magnetism),
    MasterOfStrategy(shared::master_of_strategy::MasterOfStrategy),
    //Mayhem(shared::mayhem::Mayhem),
    //Metamorphosis(shared::metamorphosis::Metamorphosis),
    //Panache(shared::panache::Panache),
    //SadisticNature(shared::sadistic_nature::SadisticNature),
    //SecretTechnique(shared::secret_technique::SecretTechnique),
    //SecretWeapon(shared::secret_weapon::SecretWeapon),
    //TheBomb(shared::the_bomb::TheBomb),
    //ThinkingAhead(shared::thinking_ahead::ThinkingAhead),
    //Transmutation(shared::transmutation::Transmutation),
    //Violence(shared::violence::Violence),
    Regret(shared::regret::Regret),
    Shame(shared::shame::Shame),
    //Writhe(shared::writhe::Writhe),
    Clumsy(shared::clumsy::Clumsy),
    //CurseOfTheBell(shared::curse_of_the_bell::CurseOfTheBell),
    Decay(shared::decay::Decay),
    Doubt(shared::doubt::Doubt),
    Injury(shared::injury::Injury),
    //Normality(shared::normality::Normality),
    //Pain(shared::pain::Pain),
    //Parasite(shared::parasite::Parasite),
    //Necronomicurse(shared::necronomicurse::Necronomicurse),
    Slimed(shared::slimed::Slimed),
    Burn(shared::burn::Burn),
    Wound(shared::wound::Wound),
    Dazed(shared::dazed::Dazed),
    AscendersBane(shared::ascenders_bane::AscendersBane),
}

impl ConcreteCard {
    pub fn inner(&self) -> &dyn Card {
        match self {
            ConcreteCard::Strike(card) => card,
            ConcreteCard::Defend(card) => card,
            ConcreteCard::Bash(card) => card,
            ConcreteCard::Void(card) => card,
            ConcreteCard::ShrugItOff(card) => card,
            ConcreteCard::Cleave(card) => card,
            ConcreteCard::Clothesline(card) => card,
            ConcreteCard::Carnage(card) => card,
            ConcreteCard::Anger(card) => card,
            ConcreteCard::GhostlyArmor(card) => card,
            ConcreteCard::Barricade(card) => card,
            ConcreteCard::Armaments(card) => card,
            ConcreteCard::Bloodletting(card) => card,
            ConcreteCard::BodySlam(card) => card,
            ConcreteCard::Bludgeon(card) => card,
            ConcreteCard::Impervious(card) => card,
            ConcreteCard::Clash(card) => card,
            //ConcreteCard::Flex(card) => card,
            ConcreteCard::Havoc(card) => card,
            //ConcreteCard::Headbutt(card) => card,
            ConcreteCard::HeavyBlade(card) => card,
            ConcreteCard::IronWave(card) => card,
            ConcreteCard::PerfectedStrike(card) => card,
            ConcreteCard::PommelStrike(card) => card,
            ConcreteCard::SwordBoomerang(card) => card,
            ConcreteCard::ThunderClap(card) => card,
            ConcreteCard::TrueGrit(card) => card,
            ConcreteCard::TwinStrike(card) => card,
            //ConcreteCard::BloodForBlood(card) => card,
            ConcreteCard::BurningPact(card) => card,
            //ConcreteCard::Combust(card) => card,
            ConcreteCard::DarkEmbrace(card) => card,
            ConcreteCard::Disarm(card) => card,
            //ConcreteCard::Dropkick(card) => card,
            //ConcreteCard::DualWield(card) => card,
            ConcreteCard::Entrench(card) => card,
            ConcreteCard::Evolve(card) => card,
            ConcreteCard::FeelNoPain(card) => card,
            ConcreteCard::FireBreathing(card) => card,
            //ConcreteCard::FlameBarrier(card) => card,
            ConcreteCard::HemoKinesis(card) => card,
            //ConcreteCard::InfernalBlade(card) => card,
            ConcreteCard::Inflame(card) => card,
            ConcreteCard::Intimidate(card) => card,
            ConcreteCard::Metallicize(card) => card,
            ConcreteCard::PowerThrough(card) => card,
            ConcreteCard::Pummel(card) => card,
            ConcreteCard::Rage(card) => card,
            ConcreteCard::Rampage(card) => card,
            ConcreteCard::RecklessCharge(card) => card,
            //ConcreteCard::Rupture(card) => card,
            ConcreteCard::SearingBlow(card) => card,
            //ConcreteCard::SecondWind(card) => card,
            ConcreteCard::SeeingRed(card) => card,
            //ConcreteCard::Sentinel(card) => card,
            //ConcreteCard::SeverSoul(card) => card,
            ConcreteCard::Shockwave(card) => card,
            //ConcreteCard::SpotWeakness(card) => card,
            ConcreteCard::Uppercut(card) => card,
            //ConcreteCard::Whirlwind(card) => card,
            ConcreteCard::Berserk(card) => card,
            //ConcreteCard::Brutality(card) => card,
            ConcreteCard::DemonForm(card) => card,
            //ConcreteCard::DoubleTap(card) => card,
            //ConcreteCard::Exhume(card) => card,
            //ConcreteCard::Feed(card) => card,
            //ConcreteCard::FiendFire(card) => card,
            //ConcreteCard::Juggernaut(card) => card,
            //ConcreteCard::LimitBreak(card) => card,
            ConcreteCard::Offering(card) => card,
            ConcreteCard::Apparition(card) => card,
            //ConcreteCard::BandageUp(card) => card,
            //ConcreteCard::Blind(card) => card,
            //ConcreteCard::DarkShackles(card) => card,
            //ConcreteCard::DeepBreath(card) => card,
            //ConcreteCard::Discovery(card) => card,
            //ConcreteCard::DramaticEntrance(card) => card,
            //ConcreteCard::Enlightenment(card) => card,
            //ConcreteCard::Finesse(card) => card,
            //ConcreteCard::FlashOfSteel(card) => card,
            //ConcreteCard::Forethought(card) => card,
            //ConcreteCard::GoodInstincts(card) => card,
            //ConcreteCard::Impatience(card) => card,
            //ConcreteCard::JackOfAllTrades(card) => card,
            //ConcreteCard::Madness(card) => card,
            //ConcreteCard::MindBlast(card) => card,
            //ConcreteCard::Panacea(card) => card,
            //ConcreteCard::PanicButton(card) => card,
            //ConcreteCard::Purity(card) => card,
            //ConcreteCard::SwiftStrike(card) => card,
            //ConcreteCard::Trip(card) => card,
            //ConcreteCard::Apotheosis(card) => card,
            //ConcreteCard::Chrysalis(card) => card,
            //ConcreteCard::HandOfGreed(card) => card,
            //ConcreteCard::Magnetism(card) => card,
            ConcreteCard::MasterOfStrategy(card) => card,
            //ConcreteCard::Mayhem(card) => card,
            //ConcreteCard::Metamorphosis(card) => card,
            //ConcreteCard::Panache(card) => card,
            //ConcreteCard::SadisticNature(card) => card,
            //ConcreteCard::SecretTechnique(card) => card,
            //ConcreteCard::SecretWeapon(card) => card,
            //ConcreteCard::TheBomb(card) => card,
            //ConcreteCard::ThinkingAhead(card) => card,
            //ConcreteCard::Transmutation(card) => card,
            //ConcreteCard::Violence(card) => card,
            ConcreteCard::WarCry(card) => card,
            ConcreteCard::WildStrike(card) => card,
            ConcreteCard::BattleTrance(card) => card,
            ConcreteCard::Regret(card) => card,
            ConcreteCard::Shame(card) => card,
            ConcreteCard::Clumsy(card) => card,
            ConcreteCard::Decay(card) => card,
            ConcreteCard::Doubt(card) => card,
            ConcreteCard::Injury(card) => card,
            //ConcreteCard::Normality(card) => card,
            //ConcreteCard::Pain(card) => card,
            //ConcreteCard::Parasite(card) => card,
            //ConcreteCard::Necronomicurse(card) => card,
            ConcreteCard::Slimed(card) => card,
            ConcreteCard::Burn(card) => card,
            ConcreteCard::Wound(card) => card,
            ConcreteCard::Dazed(card) => card,
            ConcreteCard::AscendersBane(card) => card,
        }
    }

    pub fn inner_mut(&mut self) -> &mut dyn Card {
        match self {
            ConcreteCard::Strike(card) => card,
            ConcreteCard::Defend(card) => card,
            ConcreteCard::Bash(card) => card,
            ConcreteCard::Void(card) => card,
            ConcreteCard::ShrugItOff(card) => card,
            ConcreteCard::Cleave(card) => card,
            ConcreteCard::Clothesline(card) => card,
            ConcreteCard::Carnage(card) => card,
            ConcreteCard::Anger(card) => card,
            ConcreteCard::GhostlyArmor(card) => card,
            ConcreteCard::Barricade(card) => card,
            ConcreteCard::Armaments(card) => card,
            ConcreteCard::Bloodletting(card) => card,
            ConcreteCard::BodySlam(card) => card,
            ConcreteCard::Bludgeon(card) => card,
            ConcreteCard::Impervious(card) => card,
            ConcreteCard::Clash(card) => card,
            //ConcreteCard::Flex(card) => card,
            ConcreteCard::Havoc(card) => card,
            //ConcreteCard::Headbutt(card) => card,
            ConcreteCard::HeavyBlade(card) => card,
            ConcreteCard::IronWave(card) => card,
            ConcreteCard::PerfectedStrike(card) => card,
            ConcreteCard::PommelStrike(card) => card,
            ConcreteCard::SwordBoomerang(card) => card,
            ConcreteCard::ThunderClap(card) => card,
            ConcreteCard::TrueGrit(card) => card,
            ConcreteCard::TwinStrike(card) => card,
            //ConcreteCard::BloodForBlood(card) => card,
            ConcreteCard::BurningPact(card) => card,
            //ConcreteCard::Combust(card) => card,
            ConcreteCard::DarkEmbrace(card) => card,
            ConcreteCard::Disarm(card) => card,
            //ConcreteCard::Dropkick(card) => card,
            //ConcreteCard::DualWield(card) => card,
            ConcreteCard::Entrench(card) => card,
            ConcreteCard::Evolve(card) => card,
            ConcreteCard::FeelNoPain(card) => card,
            ConcreteCard::FireBreathing(card) => card,
            //ConcreteCard::FlameBarrier(card) => card,
            ConcreteCard::HemoKinesis(card) => card,
            //ConcreteCard::InfernalBlade(card) => card,
            ConcreteCard::Inflame(card) => card,
            ConcreteCard::Intimidate(card) => card,
            ConcreteCard::Metallicize(card) => card,
            ConcreteCard::PowerThrough(card) => card,
            ConcreteCard::Pummel(card) => card,
            ConcreteCard::Rage(card) => card,
            ConcreteCard::Rampage(card) => card,
            ConcreteCard::RecklessCharge(card) => card,
            //ConcreteCard::Rupture(card) => card,
            ConcreteCard::SearingBlow(card) => card,
            //ConcreteCard::SecondWind(card) => card,
            ConcreteCard::SeeingRed(card) => card,
            //ConcreteCard::Sentinel(card) => card,
            //ConcreteCard::SeverSoul(card) => card,
            ConcreteCard::Shockwave(card) => card,
            //ConcreteCard::SpotWeakness(card) => card,
            ConcreteCard::Uppercut(card) => card,
            //ConcreteCard::Whirlwind(card) => card,
            ConcreteCard::Berserk(card) => card,
            //ConcreteCard::Brutality(card) => card,
            ConcreteCard::DemonForm(card) => card,
            //ConcreteCard::DoubleTap(card) => card,
            //ConcreteCard::Exhume(card) => card,
            //ConcreteCard::Feed(card) => card,
            //ConcreteCard::FiendFire(card) => card,
            //ConcreteCard::Juggernaut(card) => card,
            //ConcreteCard::LimitBreak(card) => card,
            ConcreteCard::Offering(card) => card,
            ConcreteCard::Apparition(card) => card,
            //ConcreteCard::BandageUp(card) => card,
            //ConcreteCard::Blind(card) => card,
            //ConcreteCard::DarkShackles(card) => card,
            //ConcreteCard::DeepBreath(card) => card,
            //ConcreteCard::Discovery(card) => card,
            //ConcreteCard::DramaticEntrance(card) => card,
            //ConcreteCard::Enlightenment(card) => card,
            //ConcreteCard::Finesse(card) => card,
            //ConcreteCard::FlashOfSteel(card) => card,
            //ConcreteCard::Forethought(card) => card,
            //ConcreteCard::GoodInstincts(card) => card,
            //ConcreteCard::Impatience(card) => card,
            //ConcreteCard::JackOfAllTrades(card) => card,
            //ConcreteCard::Madness(card) => card,
            //ConcreteCard::MindBlast(card) => card,
            //ConcreteCard::Panacea(card) => card,
            //ConcreteCard::PanicButton(card) => card,
            //ConcreteCard::Purity(card) => card,
            //ConcreteCard::SwiftStrike(card) => card,
            //ConcreteCard::Trip(card) => card,
            //ConcreteCard::Apotheosis(card) => card,
            //ConcreteCard::Chrysalis(card) => card,
            //ConcreteCard::HandOfGreed(card) => card,
            //ConcreteCard::Magnetism(card) => card,
            ConcreteCard::MasterOfStrategy(card) => card,
            //ConcreteCard::Mayhem(card) => card,
            //ConcreteCard::Metamorphosis(card) => card,
            //ConcreteCard::Panache(card) => card,
            //ConcreteCard::SadisticNature(card) => card,
            //ConcreteCard::SecretTechnique(card) => card,
            //ConcreteCard::SecretWeapon(card) => card,
            //ConcreteCard::TheBomb(card) => card,
            //ConcreteCard::ThinkingAhead(card) => card,
            //ConcreteCard::Transmutation(card) => card,
            //ConcreteCard::Violence(card) => card,
            ConcreteCard::WarCry(card) => card,
            ConcreteCard::WildStrike(card) => card,
            ConcreteCard::BattleTrance(card) => card,
            ConcreteCard::Regret(card) => card,
            ConcreteCard::Shame(card) => card,
            ConcreteCard::Clumsy(card) => card,
            ConcreteCard::Decay(card) => card,
            ConcreteCard::Doubt(card) => card,
            ConcreteCard::Injury(card) => card,
            //ConcreteCard::Normality(card) => card,
            //ConcreteCard::Pain(card) => card,
            //ConcreteCard::Parasite(card) => card,
            //ConcreteCard::Necronomicurse(card) => card,
            ConcreteCard::Slimed(card) => card,
            ConcreteCard::Burn(card) => card,
            ConcreteCard::Wound(card) => card,
            ConcreteCard::Dazed(card) => card,
            ConcreteCard::AscendersBane(card) => card,
        }
    }
}

pub fn make_card(name: CardName, upgraded: bool) -> Result<MasterCard, NotImplemented> {
    let card: ConcreteCard = match name {
        CardName::Strike => ConcreteCard::Strike(shared::strike::Strike(upgraded)),
        CardName::Defend => ConcreteCard::Defend(shared::defend::Defend(upgraded)),
        CardName::Bash => ConcreteCard::Bash(ironclad::bash::Bash(upgraded)),
        CardName::Void => ConcreteCard::Void(shared::void::Void),
        CardName::ShrugItOff => ConcreteCard::ShrugItOff(ironclad::shrugitoff::ShrugItOff(upgraded)),
        CardName::Cleave => ConcreteCard::Cleave(ironclad::cleave::Cleave(upgraded)),
        CardName::Clothesline => ConcreteCard::Clothesline(ironclad::clothesline::Clothesline(upgraded)),
        CardName::Carnage => ConcreteCard::Carnage(ironclad::carnage::Carnage(upgraded)),
        CardName::Anger => ConcreteCard::Anger(ironclad::anger::Anger(upgraded)),
        CardName::GhostlyArmor => ConcreteCard::GhostlyArmor(ironclad::ghostlyarmor::GhostlyArmor(upgraded)),
        CardName::Barricade => ConcreteCard::Barricade(ironclad::barricade::Barricade(upgraded)),
        CardName::Armaments => ConcreteCard::Armaments(ironclad::armaments::Armaments(upgraded)),
        CardName::Bloodletting => ConcreteCard::Bloodletting(ironclad::bloodletting::Bloodletting(upgraded)),
        CardName::BodySlam => ConcreteCard::BodySlam(ironclad::bodyslam::BodySlam(upgraded)),
        CardName::Bludgeon => ConcreteCard::Bludgeon(ironclad::bludgeon::Bludgeon(upgraded)),
        CardName::Impervious => ConcreteCard::Impervious(ironclad::impervious::Impervious(upgraded)),
        CardName::Clash => ConcreteCard::Clash(ironclad::clash::Clash(upgraded)),
        CardName::Flex => Err(NotImplemented::Card(name))?,
        CardName::Havoc => ConcreteCard::Havoc(ironclad::havoc::Havoc(upgraded)),
        CardName::Headbutt => Err(NotImplemented::Card(name))?,
        CardName::HeavyBlade => ConcreteCard::HeavyBlade(ironclad::heavyblade::HeavyBlade(upgraded)),
        CardName::IronWave => ConcreteCard::IronWave(ironclad::ironwave::IronWave(upgraded)),
        CardName::PerfectedStrike => ConcreteCard::PerfectedStrike(ironclad::perfectedstrike::PerfectedStrike(upgraded)),
        CardName::PommelStrike => ConcreteCard::PommelStrike(ironclad::pommelstrike::PommelStrike(upgraded)),
        CardName::SwordBoomerang => ConcreteCard::SwordBoomerang(ironclad::swordboomerang::SwordBoomerang(upgraded)),
        CardName::ThunderClap => ConcreteCard::ThunderClap(ironclad::thunderclap::ThunderClap(upgraded)),
        CardName::TrueGrit => ConcreteCard::TrueGrit(ironclad::truegrit::TrueGrit(upgraded)),
        CardName::TwinStrike => ConcreteCard::TwinStrike(ironclad::twinstrike::TwinStrike(upgraded)),
        CardName::BloodForBlood => Err(NotImplemented::Card(name))?,
        CardName::BurningPact => ConcreteCard::BurningPact(ironclad::burningpact::BurningPact(upgraded)),
        CardName::Combust => Err(NotImplemented::Card(name))?,
        CardName::DarkEmbrace => ConcreteCard::DarkEmbrace(ironclad::darkembrace::DarkEmbrace(upgraded)),
        CardName::Disarm => ConcreteCard::Disarm(ironclad::disarm::Disarm(upgraded)),
        CardName::Dropkick => Err(NotImplemented::Card(name))?,
        CardName::DualWield => Err(NotImplemented::Card(name))?,
        CardName::Entrench => ConcreteCard::Entrench(ironclad::entrench::Entrench(upgraded)),
        CardName::Evolve => ConcreteCard::Evolve(ironclad::evolve::Evolve(upgraded)),
        CardName::FeelNoPain => ConcreteCard::FeelNoPain(ironclad::feelnopain::FeelNoPain(upgraded)),
        CardName::FireBreathing => ConcreteCard::FireBreathing(ironclad::firebreathing::FireBreathing(upgraded)),
        CardName::FlameBarrier => Err(NotImplemented::Card(name))?,
        CardName::HemoKinesis => ConcreteCard::HemoKinesis(ironclad::hemokinesis::HemoKinesis(upgraded)),
        CardName::InfernalBlade => Err(NotImplemented::Card(name))?,
        CardName::Inflame => ConcreteCard::Inflame(ironclad::inflame::Inflame(upgraded)),
        CardName::Intimidate => ConcreteCard::Intimidate(ironclad::intimidate::Intimidate(upgraded)),
        CardName::Metallicize =>  ConcreteCard::Metallicize(ironclad::metallicize::Metallicize(upgraded)),
        CardName::PowerThrough => ConcreteCard::PowerThrough(ironclad::powerthrough::PowerThrough(upgraded)),
        CardName::Pummel => ConcreteCard::Pummel(ironclad::pummel::Pummel(upgraded)),
        CardName::Rage => ConcreteCard::Rage(ironclad::rage::Rage(upgraded)),
        CardName::Rampage => ConcreteCard::Rampage(ironclad::rampage::Rampage::new(upgraded)),
        CardName::RecklessCharge => ConcreteCard::RecklessCharge(ironclad::recklesscharge::RecklessCharge(upgraded)),
        CardName::Rupture => Err(NotImplemented::Card(name))?,
        CardName::SearingBlow => ConcreteCard::SearingBlow(ironclad::searingblow::SearingBlow(upgraded as u16)),
        CardName::SecondWind => Err(NotImplemented::Card(name))?,
        CardName::SeeingRed => ConcreteCard::SeeingRed(ironclad::seeingred::SeeingRed(upgraded)),
        CardName::Sentinel => Err(NotImplemented::Card(name))?,
        CardName::SeverSoul => Err(NotImplemented::Card(name))?,
        CardName::Shockwave => ConcreteCard::Shockwave(ironclad::shockwave::Shockwave(upgraded)),
        CardName::SpotWeakness => Err(NotImplemented::Card(name))?,
        CardName::Uppercut => ConcreteCard::Uppercut(ironclad::uppercut::Uppercut(upgraded)),
        CardName::Whirlwind => Err(NotImplemented::Card(name))?,
        CardName::Berserk => ConcreteCard::Berserk(ironclad::berserk::Berserk(upgraded)),
        CardName::Brutality => Err(NotImplemented::Card(name))?,
        CardName::Corruption => Err(NotImplemented::Card(name))?,
        CardName::DemonForm => ConcreteCard::DemonForm(ironclad::demonform::DemonForm(upgraded)),
        CardName::DoubleTap => Err(NotImplemented::Card(name))?,
        CardName::Exhume => Err(NotImplemented::Card(name))?,
        CardName::Feed => Err(NotImplemented::Card(name))?,
        CardName::FiendFire => Err(NotImplemented::Card(name))?,
        CardName::Juggernaut => Err(NotImplemented::Card(name))?,
        CardName::LimitBreak => Err(NotImplemented::Card(name))?,
        CardName::Offering => ConcreteCard::Offering(ironclad::offering::Offering(upgraded)),
        CardName::Reaper => Err(NotImplemented::Card(name))?,
        CardName::Slimed => ConcreteCard::Slimed(shared::slimed::Slimed(upgraded)),
        CardName::Burn => ConcreteCard::Burn(shared::burn::Burn(upgraded)),
        CardName::Wound => ConcreteCard::Wound(shared::wound::Wound),
        CardName::Dazed => ConcreteCard::Dazed(shared::dazed::Dazed),
        CardName::AscendersBane => ConcreteCard::AscendersBane(shared::ascenders_bane::AscendersBane),
        CardName::Clumsy => ConcreteCard::Clumsy(shared::clumsy::Clumsy),
        CardName::CurseOfTheBell => Err(NotImplemented::Card(name))?,
        CardName::Decay => ConcreteCard::Decay(shared::decay::Decay),
        CardName::Doubt => ConcreteCard::Doubt(shared::doubt::Doubt),
        CardName::Injury => ConcreteCard::Injury(shared::injury::Injury),
        CardName::Necronomicurse => Err(NotImplemented::Card(name))?,
        CardName::Normality => Err(NotImplemented::Card(name))?,
        CardName::Pain => Err(NotImplemented::Card(name))?,
        CardName::Parasite => Err(NotImplemented::Card(name))?,
        CardName::Regret => ConcreteCard::Regret(shared::regret::Regret),
        CardName::Shame => ConcreteCard::Shame(shared::shame::Shame),
        CardName::Writhe => Err(NotImplemented::Card(name))?,
        CardName::Apparition => ConcreteCard::Apparition(shared::apparition::Apparition(upgraded)),
        CardName::BandageUp => Err(NotImplemented::Card(name))?,
        CardName::Blind => Err(NotImplemented::Card(name))?,
        CardName::DarkShackles => Err(NotImplemented::Card(name))?,
        CardName::DeepBreath => Err(NotImplemented::Card(name))?,
        CardName::Discovery => Err(NotImplemented::Card(name))?,
        CardName::DramaticEntrance => Err(NotImplemented::Card(name))?,
        CardName::Enlightenment => Err(NotImplemented::Card(name))?,
        CardName::Finesse => Err(NotImplemented::Card(name))?,
        CardName::FlashOfSteel => Err(NotImplemented::Card(name))?,
        CardName::Forethought => Err(NotImplemented::Card(name))?,
        CardName::GoodInstincts => Err(NotImplemented::Card(name))?,
        CardName::Impatience => Err(NotImplemented::Card(name))?,
        CardName::JackOfAllTrades => Err(NotImplemented::Card(name))?,
        CardName::Madness => Err(NotImplemented::Card(name))?,
        CardName::MindBlast => Err(NotImplemented::Card(name))?,
        CardName::Panacea => Err(NotImplemented::Card(name))?,
        CardName::PanicButton => Err(NotImplemented::Card(name))?,
        CardName::Purity => Err(NotImplemented::Card(name))?,
        CardName::SwiftStrike => Err(NotImplemented::Card(name))?,
        CardName::Trip => Err(NotImplemented::Card(name))?,
        CardName::Apotheosis => Err(NotImplemented::Card(name))?,
        CardName::Chrysalis => Err(NotImplemented::Card(name))?,
        CardName::HandOfGreed => Err(NotImplemented::Card(name))?,
        CardName::Magnetism => Err(NotImplemented::Card(name))?,
        CardName::MasterOfStrategy => ConcreteCard::MasterOfStrategy(shared::master_of_strategy::MasterOfStrategy(upgraded)),
        CardName::Mayhem => Err(NotImplemented::Card(name))?,
        CardName::Metamorphosis => Err(NotImplemented::Card(name))?,
        CardName::Panache => Err(NotImplemented::Card(name))?,
        CardName::SadisticNature => Err(NotImplemented::Card(name))?,
        CardName::SecretTechnique => Err(NotImplemented::Card(name))?,
        CardName::SecretWeapon => Err(NotImplemented::Card(name))?,
        CardName::TheBomb => Err(NotImplemented::Card(name))?,
        CardName::ThinkingAhead => Err(NotImplemented::Card(name))?,
        CardName::Transmutation => Err(NotImplemented::Card(name))?,
        CardName::Violence => Err(NotImplemented::Card(name))?,
        CardName::WarCry => ConcreteCard::WarCry(ironclad::warcry::WarCry(upgraded)),
        CardName::WildStrike => ConcreteCard::WildStrike(ironclad::wildstrike::WildStrike(upgraded)),
        CardName::BattleTrance => ConcreteCard::BattleTrance(ironclad::battletrance::BattleTrance(upgraded)),
    };
    Ok(MasterCard {
        card,
        id: uuid::Uuid::new_v4(),
        upgraded: if upgraded {1} else {0},
    })
}
