#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub enum Events {
    BigFish,
    DeadAdventurer,
    FaceTrader,
    GoldenIdol,
    HypnotizingColoredMushrooms,
    LivingWall,
    ScrapOoze,
    ShiningLight,
    TheCleric,
    TheSsssserpent,
    WorldOfGoop,
    WingStatue,
    BonfireSpirits,
    Duplicator,
    GoldenShrine,
    Lab,
    MatchAndKeep,
    OminousForge,
    Purifier,
    TheDivineFountain,
    TheWomanInBlue,
    Transmogrifier,
    UpgradeShrine,
    WeMeetAgain,
    WheelofChange,
}
